version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./src:/code/src

  mongodb:
    image: "mongo:latest"
    restart: always
    command: mongod --auth
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: